/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_DepartamentoMigracion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Verificar;

/**
 *
 * @author Lanfor
 */
public class FRM_DepartamentoMigracion extends javax.swing.JFrame {

    Controlador_FRM_DepartamentoMigracion controlador_FRM_Migracion;
    DefaultTableModel modelo;
    public Verificar verificar;
    
    public FRM_DepartamentoMigracion()
    {
        initComponents();
        controlador_FRM_Migracion=new Controlador_FRM_DepartamentoMigracion(this);
        agregarEventos();
        modelo=new DefaultTableModel();
        jtbl_Tabla.setModel(modelo);
        colocarTitulosTabla();
    }
    
    public void colocarTitulosTabla()
    {
        String[] titulos={"Cédula","Nombre","Edad","Fecha","Priorida"};
        modelo.setColumnIdentifiers(titulos);
    }
    public void agregarEventos()
    {
        btn_Aceptar.addActionListener(controlador_FRM_Migracion);
        btn_Cancelar.addActionListener(controlador_FRM_Migracion);
        btn_Modificar.addActionListener(controlador_FRM_Migracion);
        btn_Atendiendo.addActionListener(controlador_FRM_Migracion);
        btn_Mayor.addActionListener(controlador_FRM_Migracion);
        btn_Menor.addActionListener(controlador_FRM_Migracion);
        btn_Reporte.addActionListener(controlador_FRM_Migracion);
        btn_Limpiar.addActionListener(controlador_FRM_Migracion);
    }
    
    
    public void mostarReporte(String msj)
    {
        jt_PizarraReportes.setText(msj);
    }
    
    public void limpiarPizarraReportes()
    {
        jt_PizarraReportes.setText("");
    }
    public String[] getInformacionCliente()
    {
        String[] info={jt_Cedula.getText(),jt_Nombre.getText(),jcb_Prioridad.getSelectedItem()+"",jt_Edad.getText(),jt_Fecha.getText()};
        return info;
    }
    
    public void resetGUI()
    {
        jt_Nombre.setText("");
        jt_Edad.setText("");
        jt_Cedula.setText("");
        jt_Fecha.setText("");
    }
    
    public void mensaje(String msj)
    {
        JOptionPane.showMessageDialog(this, msj);
    }
    
    public void mostrarEnPantalla(String msj)
    {
        jt_PizarraAtendiendo.setText(msj);
    }
    
    public void limpiarTabla()
    {
        while(modelo.getRowCount()>0)
        {
            modelo.removeRow(0);
        }
    }
    
    public void colocarFilas(String arreglo[])
    {
        modelo.addRow(arreglo);
    }
    
    
    public void insertarCantidadPersonas(String msj)
    {
        jl_NumeroPersonas.setText(msj);
    }
    
    public void insertarPromedio(String msj)
    {
        jl_NumeroPromedio.setText(msj);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_EntregaFichas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_Edad = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        jcb_Prioridad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        btn_Cancelar = new javax.swing.JButton();
        jt_Fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_Tabla = new javax.swing.JTable();
        btn_Menor = new javax.swing.JButton();
        btn_Mayor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_PizarraReportes = new javax.swing.JTextArea();
        btn_Reporte = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        jl_PromedioEdades = new javax.swing.JLabel();
        jl_CantidadPersonas = new javax.swing.JLabel();
        jl_NumeroPersonas = new javax.swing.JLabel();
        jl_NumeroPromedio = new javax.swing.JLabel();
        panel_LLamarCliente = new javax.swing.JPanel();
        btn_Atendiendo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_PizarraAtendiendo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Departamento de Migracion");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel5.setText("Prioridad:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        btn_Aceptar.setForeground(new java.awt.Color(0, 153, 153));
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Aceptar.png"))); // NOI18N
        btn_Aceptar.setActionCommand("Registrar");

        jcb_Prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "7600" }));

        jLabel7.setText("Cédula:");

        btn_Cancelar.setForeground(new java.awt.Color(0, 153, 153));
        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");

        jLabel4.setText("Fecha:");

        btn_Modificar.setForeground(new java.awt.Color(0, 153, 153));
        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btn_Modificar.setText("Modificar");

        javax.swing.GroupLayout panel_EntregaFichasLayout = new javax.swing.GroupLayout(panel_EntregaFichas);
        panel_EntregaFichas.setLayout(panel_EntregaFichasLayout);
        panel_EntregaFichasLayout.setHorizontalGroup(
            panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EntregaFichasLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_Nombre)
                        .addComponent(jcb_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt_Cedula)))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_EntregaFichasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_Cancelar)
                .addGap(86, 86, 86)
                .addComponent(btn_Modificar)
                .addGap(108, 108, 108))
        );
        panel_EntregaFichasLayout.setVerticalGroup(
            panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_EntregaFichasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcb_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_EntregaFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Cancelar)
                        .addComponent(btn_Modificar))
                    .addComponent(btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );

        jTabbedPane1.addTab("Entrega de Fichas", panel_EntregaFichas);

        jtbl_Tabla.setBackground(new java.awt.Color(51, 51, 51));
        jtbl_Tabla.setFont(new java.awt.Font("HP Simplified", 2, 18)); // NOI18N
        jtbl_Tabla.setForeground(new java.awt.Color(0, 255, 255));
        jtbl_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbl_Tabla);

        btn_Menor.setText("<");

        btn_Mayor.setText(">");

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Ordenar Clientes por Edades");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Menor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Mayor)
                        .addGap(61, 61, 61))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Menor)
                    .addComponent(btn_Mayor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Ordenar", jPanel1);

        jt_PizarraReportes.setEditable(false);
        jt_PizarraReportes.setColumns(20);
        jt_PizarraReportes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_PizarraReportes.setForeground(new java.awt.Color(0, 153, 153));
        jt_PizarraReportes.setRows(5);
        jScrollPane4.setViewportView(jt_PizarraReportes);

        btn_Reporte.setText("Generar Reporte");
        btn_Reporte.setActionCommand("Reporte");

        btn_Limpiar.setText("Limpiar");

        jl_PromedioEdades.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jl_PromedioEdades.setForeground(new java.awt.Color(0, 204, 204));
        jl_PromedioEdades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_PromedioEdades.setText("Promedio de Edades:");

        jl_CantidadPersonas.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jl_CantidadPersonas.setForeground(new java.awt.Color(0, 204, 204));
        jl_CantidadPersonas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_CantidadPersonas.setText("Cantidad de Personas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_CantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_NumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jl_PromedioEdades, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_NumeroPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_Limpiar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Reporte))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CantidadPersonas)
                    .addComponent(jl_NumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_PromedioEdades)
                    .addComponent(jl_NumeroPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Limpiar)
                    .addComponent(btn_Reporte))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        btn_Atendiendo.setForeground(new java.awt.Color(0, 153, 153));
        btn_Atendiendo.setText("Atendiendo");

        jt_PizarraAtendiendo.setEditable(false);
        jt_PizarraAtendiendo.setColumns(20);
        jt_PizarraAtendiendo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_PizarraAtendiendo.setForeground(new java.awt.Color(0, 153, 153));
        jt_PizarraAtendiendo.setRows(5);
        jScrollPane1.setViewportView(jt_PizarraAtendiendo);

        javax.swing.GroupLayout panel_LLamarClienteLayout = new javax.swing.GroupLayout(panel_LLamarCliente);
        panel_LLamarCliente.setLayout(panel_LLamarClienteLayout);
        panel_LLamarClienteLayout.setHorizontalGroup(
            panel_LLamarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LLamarClienteLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LLamarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Atendiendo)
                .addGap(338, 338, 338))
        );
        panel_LLamarClienteLayout.setVerticalGroup(
            panel_LLamarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LLamarClienteLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btn_Atendiendo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LLamar Cliente", panel_LLamarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_DepartamentoMigracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_DepartamentoMigracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_DepartamentoMigracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_DepartamentoMigracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_DepartamentoMigracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Atendiendo;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Mayor;
    private javax.swing.JButton btn_Menor;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Reporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_Prioridad;
    private javax.swing.JLabel jl_CantidadPersonas;
    private javax.swing.JLabel jl_NumeroPersonas;
    private javax.swing.JLabel jl_NumeroPromedio;
    private javax.swing.JLabel jl_PromedioEdades;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Fecha;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextArea jt_PizarraAtendiendo;
    private javax.swing.JTextArea jt_PizarraReportes;
    private javax.swing.JTable jtbl_Tabla;
    private javax.swing.JPanel panel_EntregaFichas;
    private javax.swing.JPanel panel_LLamarCliente;
    // End of variables declaration//GEN-END:variables
}
